version: '3.5'

services:
  postgres:
    container_name: postgres_demo
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: somepassword
      POSTGRES_DB: mydb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql/0_docker_postgres_init.sql:/docker-entrypoint-initdb.d/0_docker_postgres_init.sql

    # volumes:
    #   - ./data:/var/lib/postgresql/data
    #   - ./sql/init_database.sh:/init_database.sh
    # command: ["/bin/bash", "/init_database.sh"]
    ports:
      - "5408:5432"