version: '3.5'

services:
  postgres:
    container_name: postgres_demo
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: somepassword
      POSTGRES_DB: mydb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5408:5432"